'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),D=require('../tools/draft-manager.cjs'),P=require('../tools/plan.cjs'),R=require('../tools/release.cjs');
const original=R.signature(R.capture()),shared=fs.readFileSync('reports/work-context.json','utf8'),template=fs.readFileSync('config/experiment-prompt-template.md','utf8');
const id='experiment-manager-test-'+process.pid,relative='data/drafts/experiments/'+id+'.json',draft={schemaVersion:1,id,title:'TEST ONLY',profileBinding:P.binding('experiment-balanced'),sessions:[]};
fs.mkdirSync('data/drafts/experiments',{recursive:true});fs.writeFileSync(relative,JSON.stringify(draft));
try{assert.throws(()=>D.safe('data/week03.json'),/Select/);assert.throws(()=>D.validateTemplate(template.replaceAll('{{draftPath}}','fixed.json')),/Missing/);assert.throws(()=>D.validateTemplate(template+'{{oops}}'),/Unknown/);assert.throws(()=>D.run({action:'delete',file:relative}),/confirmation/);assert.throws(()=>D.generate(relative,8),/1 to 7/);
const out=D.generate(relative,2),ctx=JSON.parse(fs.readFileSync(out.contextPath,'utf8'));assert.equal(ctx.profileHash,draft.profileBinding.profileHash);assert.equal(ctx.draft.sessionCount,2);assert.equal(ctx.profileId,'experiment-balanced');assert(out.prompt.includes(path.resolve(relative)));assert(out.prompt.includes('--file="'+relative+'"'));assert(!out.prompt.includes('{{'));assert.equal(fs.readFileSync('reports/work-context.json','utf8'),shared);assert.equal(fs.readFileSync(relative,'utf8'),JSON.stringify(draft));assert.equal(R.signature(R.capture()),original);
const exportPath=path.join(R.ROOT,'.sync/template-test.md');D.run({action:'export',file:exportPath});assert.equal(fs.readFileSync(exportPath,'utf8'),template);const imported=D.run({action:'import',file:exportPath});assert(fs.existsSync(imported.backup));assert.equal(fs.readFileSync('config/experiment-prompt-template.md','utf8').replace(/^\uFEFF/,''),template.replace(/^\uFEFF/,''));fs.unlinkSync(exportPath);fs.unlinkSync(imported.backup);
if(process.platform==='win32'){D.run({action:'delete',file:relative,confirm:true});assert(!fs.existsSync(relative));}console.log('PASS selected path, snapshot binding, dedicated context, no shared overwrite, template import/export/rejection, recycle deletion and formal bytes preserved');
}finally{fs.writeFileSync('config/experiment-prompt-template.md',template);if(fs.existsSync(relative))fs.unlinkSync(relative);const out=path.resolve('reports/experiment-contexts',id);assert(path.dirname(out)===path.resolve('reports/experiment-contexts'));fs.rmSync(out,{recursive:true,force:true});}
