'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),assert=require('node:assert/strict'),R=require('../tools/release.cjs');
const files=R.capture(),sig=R.signature(files),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'n2-manager-'));
try{for(const p of ['tools','schemas','config','data/reference'])fs.cpSync(path.join(R.ROOT,p),path.join(tmp,p),{recursive:true});fs.copyFileSync(path.join(R.ROOT,'weekly.js'),path.join(tmp,'weekly.js'));R.writeChanged(tmp,{...files,...R.metadata(files)});
const code=`const fs=require('fs'),assert=require('assert/strict'),M=require('./tools/manager.cjs'),P=require('./tools/plan.cjs'),R=require('./tools/release.cjs');
const official=P.load('official-default'),before=R.signature(R.capture());const source=P.save({...official,id:'experiment-adopt-test',name:'Adoption test',mode:'experiment',vocabularyPerDay:official.vocabularyPerDay+1},{create:true});
const old=M.run({action:'new',mode:'official'}),oldText=fs.readFileSync(old.file,'utf8');assert.equal(JSON.parse(oldText).profileBinding.profileHash,P.binding('official-default').profileHash);
const exp=M.run({action:'new',mode:'experiment',profile:source.id,id:'experiment-adopt-fixture'}),expText=fs.readFileSync(exp.file,'utf8');const preview=M.run({action:'adopt-preview',id:source.id});assert(preview.changes.some(c=>c.field==='vocabularyPerDay'));assert.throws(()=>M.run({action:'adopt',id:source.id,confirm:true,sourceHash:'bad',officialHash:preview.officialHash}),/changed/);
const adopted=M.run({action:'adopt',id:source.id,confirm:true,sourceHash:preview.sourceHash,officialHash:preview.officialHash});assert.equal(P.load('official-default').vocabularyPerDay,source.vocabularyPerDay);assert.equal(JSON.parse(fs.readFileSync(adopted.backup,'utf8')).vocabularyPerDay,official.vocabularyPerDay);assert.equal(fs.readFileSync(old.file,'utf8'),oldText);assert.equal(fs.readFileSync(exp.file,'utf8'),expText);assert.equal(R.signature(R.capture()),before);
const result=M.run({action:'generate',mode:'official',file:old.file});const context=JSON.parse(fs.readFileSync(result.contextPath,'utf8'));assert.equal(context.parameters.vocabularyPerDay,official.vocabularyPerDay);assert(result.prompt.includes(old.file));assert(!result.prompt.includes('{{'));assert.throws(()=>M.run({action:'new',mode:'official'}),/EEXIST/);assert.throws(()=>M.run({action:'validate',mode:'official',file:old.file}));assert.throws(()=>M.checked({mode:'official',file:'data/week03.json'}),/draft/);
fs.unlinkSync(old.file);const next=M.run({action:'new',mode:'official'});assert.equal(JSON.parse(fs.readFileSync(next.file,'utf8')).profileBinding.parameters.vocabularyPerDay,source.vocabularyPerDay);assert.equal(R.signature(R.capture()),before);console.log('PASS official adoption difference/backup, immutable existing drafts, next-draft inheritance, selected formal context, safe paths and no course mutation');`;
const run=cp.spawnSync(process.execPath,['-e',code],{cwd:tmp,encoding:'utf8',windowsHide:true,env:{...process.env,NODE_PATH:path.join(R.ROOT,'node_modules')},maxBuffer:4*1024*1024});assert.equal(run.status,0,run.stdout+run.stderr);console.log(run.stdout.trim());assert.equal(R.signature(R.capture()),sig);
}finally{const safe=fs.realpathSync(tmp);assert(safe.startsWith(fs.realpathSync(os.tmpdir())+path.sep)&&path.basename(safe).startsWith('n2-manager-'));fs.rmSync(safe,{recursive:true,force:true,maxRetries:3});}
