'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const R=require('../tools/release.cjs'),P=require('../tools/plan.cjs'),E=require('../tools/experiments.cjs');
const files=R.capture(),before=R.signature(files),active=fs.readFileSync(path.join(R.ROOT,'config/active-profile.json'),'utf8'),official=fs.readFileSync(path.join(R.ROOT,'config/profiles/official-default.json'),'utf8');
const id='experiment-test-'+process.pid,copy=id+'-copy';
try{const base=P.load('official-default'),p=P.save({...base,id,name:'Test profile',mode:'experiment'},{create:true});assert.equal(P.load(id).vocabularyPerDay,12);p.vocabularyPerDay=18;P.save(p);assert.equal(P.load(id).vocabularyPerDay,18);const b=P.binding(id);P.validateBinding(b,'experiment');P.save({...p,vocabularyPerDay:20});assert.notEqual(P.binding(id).profileHash,b.profileHash);P.validateBinding(b,'experiment');P.save({...p,id:copy},{create:true});assert.equal(P.load(copy).vocabularyPerDay,18);assert.throws(()=>P.save({...p,vocabularyPerDay:-1}),/Invalid/);assert.throws(()=>P.remove('official-default',true),/cannot/);assert.throws(()=>P.remove(id,false),/confirmation/);assert.throws(()=>P.save({...p,id:'../escape'}),/Invalid/);P.context(copy,4);const pack=JSON.parse(fs.readFileSync(path.join(R.ROOT,'reports/work-context.json'),'utf8'));assert.equal(pack.profileId,copy);assert.equal(pack.parameters.vocabularyPerDay,18);assert.equal(pack.generationMode,'experiment');assert.equal(pack.next.experiment,true);assert(pack.candidates.vocabulary.length<=20);const stats=P.coverage();assert.equal(stats.types.vocab.n2Candidates,2518);assert.equal(stats.latestFormalDay,21);assert.equal(stats.types.kanji.coveredStableIds,null);assert.equal(stats.forecasts[0].capacity,stats.daysAvailable*12);assert(!R.AUTO('config/profiles/'+id+'.json'));assert(!R.AUTO('reports/work-context.json'));P.remove(copy,true);P.remove(id,true);
}finally{for(const name of [id,copy]){const p=path.join(R.ROOT,'config/profiles',name+'.json');if(fs.existsSync(p))fs.unlinkSync(p);}fs.writeFileSync(path.join(R.ROOT,'config/active-profile.json'),active);}
assert.equal(fs.readFileSync(path.join(R.ROOT,'config/profiles/official-default.json'),'utf8'),official);
const session=structuredClone(JSON.parse(files['data/week03.json']).days[0]);delete session.week;delete session.day;session.id='session-test';for(const v of session.vocabulary)v.examples=v.collocations.map(c=>c.text);const fixture={schemaVersion:1,id:'experiment-test-fixture',title:'TEST ONLY',profileBinding:P.binding('experiment-balanced'),sessions:[session]};E.validate(fixture);assert.throws(()=>E.validate({...fixture,profileBinding:P.binding('official-default')}),/binding/);assert.throws(()=>E.validate({...fixture,sessions:[{...session,day:22}]}),/numbers/);
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'n2-plan-'));
try{for(const p of ['tools','schemas','config','data/reference'])fs.cpSync(path.join(R.ROOT,p),path.join(tmp,p),{recursive:true});fs.copyFileSync(path.join(R.ROOT,'weekly.js'),path.join(tmp,'weekly.js'));R.writeChanged(tmp,{...files,...R.metadata(files),'data/drafts/experiments/experiment-test-fixture.json':JSON.stringify(fixture)});const result=cp.spawnSync(process.execPath,['tools/experiments.cjs','promote','--file=data/drafts/experiments/experiment-test-fixture.json'],{cwd:tmp,encoding:'utf8',windowsHide:true,env:{...process.env,NODE_PATH:path.join(R.ROOT,'node_modules')}});assert.equal(result.status,0,result.stdout+result.stderr);const index=JSON.parse(fs.readFileSync(path.join(tmp,'data/index.json'),'utf8'));assert.equal(index.weeks.length,3);assert.equal(index.experiments.length,1);assert(!index.files.some(f=>f.url.includes('draft')));for(const p of ['data/week01.json','data/week02.json','data/week03.json'])assert.equal(fs.readFileSync(path.join(tmp,p),'utf8'),files[p]);}finally{assert(fs.realpathSync(tmp).startsWith(fs.realpathSync(os.tmpdir())+path.sep));fs.rmSync(tmp,{recursive:true,force:true,maxRetries:3});}
assert.equal(R.signature(R.capture()),before);console.log('PASS Profile CRUD/protection/hash, profile-bound context, N2 forecasts, isolated experiment promotion and official bytes preserved');
