'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),R=require('./release.cjs');
const read=(p,fallback=null)=>{try{return JSON.parse(fs.readFileSync(path.join(R.ROOT,p),'utf8').replace(/^\uFEFF/,''));}catch{return fallback;}};
async function main(){const mode=process.argv[2]||'local';if(mode==='pages'){const response=await fetch('https://likairesearch-jpg.github.io/N2_Daily_study_Plan/version.json?check='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('Pages HTTP '+response.status);const version=await response.json();if(!/^[a-f0-9]{64}$/.test(version.courseVersion))throw Error('Invalid Pages version');R.writeChanged(R.ROOT,{'.sync/pages-status.json':JSON.stringify({checkedAt:new Date().toISOString(),courseVersion:version.courseVersion},null,2)});}else if(mode!=='local')throw Error('Use local or pages');
 let task=null;if(process.platform==='win32'){const result=cp.spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',"$t=Get-ScheduledTask -TaskName N2-Daily-Course-Sync -ErrorAction Stop; $i=Get-ScheduledTaskInfo -TaskName $t.TaskName; @{enabled=$t.Settings.Enabled;nextRun=$i.NextRunTime.ToString('o');lastTaskRun=$i.LastRunTime.ToString('o');lastTaskResult=$i.LastTaskResult}|ConvertTo-Json -Compress"],{encoding:'utf8',windowsHide:true});if(result.status===0)task=JSON.parse(result.stdout);}
 const sync=read('.sync/status.json',{}),index=read('data/index.json',{}),ref=read('data/reference/index.json',{}),registry=read('sources/registry.json',{}),pages=read('.sync/pages-status.json');const weeks=index.weeks||[],last=weeks.at(-1),latestFetch=(registry.sources||[]).map(s=>s.fetchedAt).filter(Boolean).sort().at(-1);
 console.log(['自动课程同步: '+(task?(task.enabled?'ON':'OFF'):'unknown'),'下一次自动同步: '+(task?.nextRun||'unknown'),'上一次同步尝试: '+(sync.time||'unknown'),'上一次成功 push: '+(sync.lastSuccessfulPushAt||'unknown（旧记录未保存此字段）'),'上一次失败原因: '+(sync.lastFailureReason||'无已记录失败'),'当前同步结果: '+(sync.message||'unknown'),'当前正式课程: Week '+(last?.week||'unknown')+' / '+(last?.days?.at(-1)||'unknown'),'本地课程版本: '+(read('version.json',{}).courseVersion||'unknown'),'Pages 部署课程版本: '+(pages?.courseVersion||'unknown；点击“检查 Pages 版本”联网查看'),'Pages 检查时间: '+(pages?.checkedAt||'unknown（不会在打开窗口时联网）'),'Reference snapshot: '+(ref.version||'unknown'),'Reference 最近源获取时间: '+(latestFetch||'unknown'),'Reference 策略: 本地读取，仅手动更新；版本未变化时获取时间保持原值。'].join('\n'));
}
main().catch(e=>{console.error('STATUS FAILED: '+e.message);process.exitCode=1;});
