'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),R=require('./release.cjs'),P=require('./plan.cjs');
const root=R.ROOT,dir=path.join(root,'data/drafts/experiments'),template=path.join(root,'config/experiment-prompt-template.md');
const tokens=['projectRoot','draftPath','draftRelative','contextPath','latestFormal','latestCoursePath','profileId','profileHash','targetLevel','sessionCount','vocabularyCount','grammarCount','readingCount','listeningCount','validateCommand'];
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
function safe(file){const p=path.resolve(root,file);if(path.dirname(p)!==dir||!/^experiment-[a-z0-9-]+\.json$/.test(path.basename(p)))throw Error('Select a JSON draft directly inside data/drafts/experiments');if(fs.realpathSync(p)!==p||fs.lstatSync(p).isSymbolicLink())throw Error('Linked drafts are not supported');return p;}
function checked(file){const p=safe(file),d=read(p);if(d.schemaVersion!==1||!Array.isArray(d.sessions)||d.id!==path.basename(p,'.json'))throw Error('Invalid draft structure or filename/id mismatch');P.validateBinding(d.profileBinding,'experiment');return {p,d};}
function validateTemplate(t){if(typeof t!=='string'||!t.trim()||Buffer.byteLength(t)>100000)throw Error('Template must be nonempty UTF-8 text under 100KB');const used=[...t.matchAll(/{{\s*([^{}]+?)\s*}}/g)].map(m=>m[1]);for(const k of tokens)if(!used.includes(k))throw Error('Missing template placeholder: {{'+k+'}}');for(const k of used)if(!tokens.includes(k))throw Error('Unknown template placeholder: {{'+k+'}}');if(t.replace(/{{\s*[^{}]+?\s*}}/g,'').match(/{{|}}/))throw Error('Malformed template placeholder');return t;}
function list(){if(!fs.existsSync(dir))return [];return fs.readdirSync(dir).filter(f=>/^experiment-[a-z0-9-]+\.json$/.test(f)).map(f=>{const file=path.join(dir,f);try{const {d}=checked(file);return {file,name:f,modified:fs.statSync(file).mtime.toISOString(),sessions:d.sessions.length,profile:d.profileBinding.profileId,parameters:d.profileBinding.parameters};}catch(e){return {file,name:f,error:e.message};}});}
function generate(file,count){const {p,d}=checked(file);if(!Number.isInteger(count)||count<1||count>7)throw Error('Session count must be 1 to 7');if(count<d.sessions.length)throw Error('Target count is below existing sessions; choose a larger count. No content was removed.');const t=validateTemplate(fs.readFileSync(template,'utf8')),b=d.profileBinding,params=b.parameters;
const weeks=R.validate(R.capture()).weeks;const pack=require('./workflow.cjs').context(weeks.at(-1).week+1,{persist:false});Object.assign(pack,structuredClone(b),{profileBinding:structuredClone(b),generationMode:'experiment',draft:{file:p,id:d.id,sessionCount:count},next:{experiment:true,suggestedSessions:count}});pack.rules.push('Only edit the selected experiment draft; never modify formal courses. Profile snapshot belongs to this draft, not the active Profile.');
const relative=path.relative(root,p).split(path.sep).join('/'),out=path.join(root,'reports/experiment-contexts',d.id),contextPath=path.join(out,'work-context.json');const vals={projectRoot:root,draftPath:p,draftRelative:relative,contextPath,latestFormal:'Week '+pack.latestFormal.week+' / Day '+pack.latestFormal.day,latestCoursePath:path.join(root,pack.handoff.source),profileId:b.profileId,profileHash:b.profileHash,targetLevel:params.targetJlptLevel,sessionCount:count,vocabularyCount:params.vocabularyPerDay,grammarCount:params.grammarPerDay,readingCount:params.readingQuestionsPerDay,listeningCount:params.listeningQuestionsPerDay,validateCommand:'node tools/experiments.cjs validate --file="'+relative+'"'};
const prompt=t.replace(/{{\s*([^{}]+?)\s*}}/g,(_,k)=>String(vals[k]));if(Buffer.byteLength(JSON.stringify(pack))>120000)throw Error('Context exceeds size limit');fs.mkdirSync(out,{recursive:true});R.writeChanged(root,{[path.relative(root,contextPath)]:JSON.stringify(pack,null,2)+'\n',[path.relative(root,path.join(out,'work-instruction.txt'))]:prompt});return {prompt,contextPath,promptPath:path.join(out,'work-instruction.txt')};}
function remove(file){const p=safe(file);if(process.platform!=='win32')throw Error('Recycle Bin deletion requires Windows');const code="Add-Type -AssemblyName Microsoft.VisualBasic; [Microsoft.VisualBasic.FileIO.FileSystem]::DeleteFile('"+p.replace(/'/g,"''")+"',[Microsoft.VisualBasic.FileIO.UIOption]::OnlyErrorDialogs,[Microsoft.VisualBasic.FileIO.RecycleOption]::SendToRecycleBin,[Microsoft.VisualBasic.FileIO.UICancelOption]::ThrowException)";const r=cp.spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-EncodedCommand',Buffer.from(code,'utf16le').toString('base64')],{encoding:'utf8',windowsHide:true});if(r.status!==0)throw Error(r.stderr||'Recycle failed; no permanent deletion attempted');return {deleted:p};}
function run(q){if(q.action==='list')return list();if(q.action==='generate')return generate(q.file,q.count);if(q.action==='delete'){if(q.confirm!==true)throw Error('Deletion requires confirmation');return remove(q.file);}if(q.action==='export'){if(!/\.(md|txt)$/i.test(q.file)||path.resolve(q.file)===template)throw Error('Export to a separate .md or .txt file');fs.writeFileSync(q.file,fs.readFileSync(template));return {exported:q.file};}if(q.action==='import'){const t=validateTemplate(fs.readFileSync(q.file,'utf8').replace(/^\uFEFF/,''));const backup=path.join(root,'.sync/template-backups',Date.now()+'.md');fs.mkdirSync(path.dirname(backup),{recursive:true});fs.copyFileSync(template,backup);fs.writeFileSync(template,t);return {imported:template,backup,note:'Regenerate instructions to use the imported template.'};}throw Error('Unknown action');}
module.exports={safe,checked,validateTemplate,list,generate,run,tokens};
if(require.main===module)try{console.log(JSON.stringify(run(read(process.argv[2]))));}catch(e){console.error('DRAFT MANAGER FAILED: '+e.message);process.exitCode=1;}
