'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),R=require('./release.cjs'),P=require('./plan.cjs'),W=require('./workflow.cjs'),D=require('./draft-manager.cjs');
const root=R.ROOT,read=p=>JSON.parse(fs.readFileSync(path.resolve(root,p),'utf8').replace(/^\uFEFF/,''));
function git(args){const r=cp.spawnSync('git',args,{cwd:root,encoding:'utf8',windowsHide:true,maxBuffer:32*1024*1024});if(r.status!==0)throw Error(r.stderr||'Git failed');return r.stdout.trim();}
function mainOnly(){if(git(['branch','--show-current'])!=='main')throw Error('Development workspace: publishing and scheduled-task controls are disabled. Use the main directory manager.');}
function child(script,...args){const r=cp.spawnSync(process.execPath,[script,...args],{cwd:root,encoding:'utf8',windowsHide:true,maxBuffer:4*1024*1024});if(r.status!==0)throw Error(r.stdout+r.stderr);return r.stdout.trim();}
function adoptPreview(id){const p=P.load(id);if(p.mode!=='experiment')throw Error('Select a saved experiment Profile');const old=P.load('official-default'),keys=[...new Set([...Object.keys(p),...Object.keys(old)])].filter(k=>!['id','name','mode','schemaVersion','createdAt','updatedAt'].includes(k));return {source:p.id,sourceHash:P.hash(P.canonical(p)),officialHash:P.hash(P.canonical(old)),changes:keys.filter(k=>JSON.stringify(p[k])!==JSON.stringify(old[k])).map(k=>({field:k,before:old[k]??null,after:p[k]??null})),note:'Only future formal drafts change. Existing drafts and course files retain their snapshots.'};}
function adopt(q){if(!q.confirm)throw Error('Confirmation required');const preview=adoptPreview(q.id);if(q.sourceHash!==preview.sourceHash||q.officialHash!==preview.officialHash)throw Error('Profiles changed since preview. Review differences again.');const previous=P.load('official-default'),source=P.load(q.id),backup=path.join(root,'.sync/official-profile-backups',Date.now()+'.json');fs.mkdirSync(path.dirname(backup),{recursive:true});fs.writeFileSync(backup,JSON.stringify(previous,null,2)+'\n',{flag:'wx'});const updated=P.save({...source,id:'official-default',mode:'official',name:'正式方案：'+source.name,createdAt:previous.createdAt});return {message:'已设为正式学习方案，仅用于以后新建的正式草稿。',backup,profile:updated};}
function mode(q){if(!['official','experiment'].includes(q.mode))throw Error('Select official or experiment mode');return q.mode;}
function checked(q){const m=mode(q);if(m==='experiment')return D.checked(q.file);const p=path.resolve(root,q.file);if(path.dirname(p)!==path.join(root,'data/drafts')||!/^week\d{2,}\.json$/.test(path.basename(p))||fs.realpathSync(p)!==p)throw Error('Select a formal draft inside data/drafts');const d=read(p);if(d.week!==Number(path.basename(p).match(/\d+/)[0])||!Array.isArray(d.days))throw Error('Draft week/filename mismatch');if(d.profileBinding)P.validateBinding(d.profileBinding,'official');else if(d.week>3)throw Error('Formal draft requires a saved official Profile binding');return {p,d};}
function drafts(m){if(m==='experiment')return D.list();if(m!=='official')throw Error('Invalid mode');const dir=path.join(root,'data/drafts');if(!fs.existsSync(dir))return [];return fs.readdirSync(dir).filter(f=>/^week\d{2,}\.json$/.test(f)).map(name=>{const file=path.join(dir,name);try{const {d}=checked({mode:m,file});return {file,name,sessions:d.days.length,profile:d.profileBinding?.profileId||'历史草稿（无配置快照）',parameters:d.profileBinding?.parameters,modified:fs.statSync(file).mtime.toISOString()};}catch(e){return {file,name,error:e.message};}});}
function create(q){const m=mode(q);let d,file;if(m==='experiment'){const b=P.binding(q.profile);if(b.profileMode!=='experiment')throw Error('Choose a saved experiment Profile in the Learning Plan page');if(!/^experiment-[a-z0-9-]{1,48}$/.test(q.id))throw Error('ID must start with experiment- and use lowercase letters, digits or hyphens');file='data/drafts/experiments/'+q.id+'.json';d={schemaVersion:1,id:q.id,title:b.profileName,profileBinding:b,sessions:[]};}else{const week=R.validate(R.capture()).weeks.at(-1).week+1;file='data/drafts/week'+String(week).padStart(2,'0')+'.json';d={schemaVersion:'2.1.0',week,profileBinding:P.binding('official-default'),days:[]};}fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),JSON.stringify(d,null,2)+'\n',{flag:'wx'});return {message:'空白草稿已建立，需交给 Work 填写课程。',file:path.join(root,file)};}
const formalTokens=['projectRoot','draftPath','contextPath','profileId','profileHash','week','startDay','endDay','startDate','endDate','vocabularyCount','grammarCount','readingCount','listeningCount','validateCommand'];
function validateFormal(t){for(const k of formalTokens)if(!t.includes('{{'+k+'}}'))throw Error('Missing placeholder: {{'+k+'}}');for(const match of t.matchAll(/{{([^{}]+)}}/g))if(!formalTokens.includes(match[1]))throw Error('Unknown placeholder: '+match[1]);if(Buffer.byteLength(t)>100000)throw Error('Template too large');return t;}
function generate(q){const {p,d}=checked(q);if(q.mode==='experiment')return D.generate(p,q.count);if(!d.profileBinding)throw Error('Historical draft has no Profile snapshot. Create a new formal draft for the next Week; historical content is not rebound automatically.');const pack=W.context(d.week,{persist:false}),b=d.profileBinding,par=b.parameters;Object.assign(pack,structuredClone(b),{profileBinding:structuredClone(b),generationMode:'official',draft:{file:p,week:d.week}});const out='reports/formal-contexts/week'+String(d.week).padStart(2,'0'),contextPath=path.join(root,out,'work-context.json');const v={projectRoot:root,draftPath:p,contextPath,profileId:b.profileId,profileHash:b.profileHash,week:d.week,...pack.next,vocabularyCount:par.vocabularyPerDay,grammarCount:par.grammarPerDay,readingCount:par.readingQuestionsPerDay,listeningCount:par.listeningQuestionsPerDay,validateCommand:'node tools/workflow.cjs validate --week='+d.week};const template=validateFormal(fs.readFileSync(path.join(root,'config/formal-prompt-template.md'),'utf8'));const prompt=template.replace(/{{([^{}]+)}}/g,(_,k)=>String(v[k]));if(Buffer.byteLength(JSON.stringify(pack))>120000)throw Error('Context exceeds size limit');R.writeChanged(root,{[out+'/work-context.json']:JSON.stringify(pack,null,2)+'\n',[out+'/work-instruction.txt']:prompt});return {prompt,contextPath,message:'已生成所选草稿的专用材料；复制给 Work 执行。'};}
function template(q){const m=mode(q),target=path.join(root,'config/'+(m==='official'?'formal':'experiment')+'-prompt-template.md');if(!/\.(md|txt)$/i.test(q.file)||path.resolve(q.file)===target)throw Error('Select a separate .md or .txt file');if(q.action==='template-export'){fs.writeFileSync(q.file,fs.readFileSync(target));return {message:'模板已导出',file:q.file};}if(!q.confirm)throw Error('Confirmation required');const t=fs.readFileSync(q.file,'utf8').replace(/^\uFEFF/,'');if(m==='official')validateFormal(t);else D.validateTemplate(t);const backup=path.join(root,'.sync/template-backups',m+'-'+Date.now()+'.md');fs.mkdirSync(path.dirname(backup),{recursive:true});fs.copyFileSync(target,backup);fs.writeFileSync(target,t);return {message:'模板已导入；重新生成指令后生效。',backup};}
function pending(){const files=R.capture(),tracked=new Set(git(['ls-files','--','data','version.json']).split('\n')),changes=[];let validation='已批准';try{R.assertPublished(files);}catch(e){validation=e.message;}
for(const [p,text] of Object.entries(files).filter(([p])=>/^data\/(week\d+\.json|experiments\/experiment-[a-z0-9-]+\.json)$/.test(p))){const old=tracked.has(p)?git(['show','HEAD:'+p]):null;if(old===null||old!==text.trim())changes.push({file:p,state:old===null?'待新增':'待更新'});}
const approvals=read('data/publication.json');for(const p of tracked)if(p.startsWith('data/experiments/')&&!files[p])changes.push({file:p,state:approvals.withdrawals?.[p]?'待撤下':'未授权删除'});const unpushed=git(['rev-list','--count','origin/main..HEAD']);return {changes,validation,unpushedCommits:Number(unpushed),experiments:Object.keys(files).filter(p=>p.startsWith('data/experiments/')),note:'列表为相对本地 HEAD 的变化；未推送提交和 Pages 部署状态另列。'};}
function run(q){switch(q.action){case 'profiles':return {profiles:fs.readdirSync(path.join(root,'config/profiles')).filter(f=>f.endsWith('.json')).map(f=>P.load(f.slice(0,-5))),active:read('config/active-profile.json').id};case 'adopt-preview':return adoptPreview(q.id);case 'adopt':return adopt(q);case 'list':return drafts(mode(q));case 'new':return create(q);case 'generate':return generate(q);case 'validate':case 'promote':{const {p,d}=checked(q);let result;if(q.mode==='official')result=W.draft(d.week,q.action==='promote');else result=q.action==='promote'?require('./experiments.cjs').promote(p):{validated:!!require('./experiments.cjs').validate(d)};return {message:q.action==='promote'?'本地晋升成功，尚未发布到网站。':'草稿校验通过，尚未晋升或发布。',result};}
case 'delete':if(!q.confirm)throw Error('Confirmation required');if(q.mode==='experiment')return D.run(q);else{const {p}=checked(q);const code="Add-Type -AssemblyName Microsoft.VisualBasic; [Microsoft.VisualBasic.FileIO.FileSystem]::DeleteFile('"+p.replace(/'/g,"''")+"','OnlyErrorDialogs','SendToRecycleBin','ThrowException')";const r=cp.spawnSync('powershell.exe',['-NoProfile','-EncodedCommand',Buffer.from(code,'utf16le').toString('base64')],{encoding:'utf8',windowsHide:true});if(r.status!==0)throw Error(r.stderr);return {message:'草稿已移入回收站，已晋升课程未删除。'};}
case 'template-import':case 'template-export':return template(q);
case 'status':return {pending:pending(),status:child('tools/dashboard.cjs',q.online?'pages':'local')};case 'sync':mainOnly();return {message:child('tools/sync.cjs','once')+'\n推送成功后仍需等待 Actions 部署，刷新发布状态核对。'};
case 'start':case 'stop':mainOnly();return {message:child('tools/sync.cjs',q.action)};case 'withdraw':mainOnly();if(!q.confirm)throw Error('Confirmation required');return require('./experiment-release.cjs').run('withdraw',q.file);
case 'reference-status':return {message:child('tools/reference.cjs','status')};case 'reference-update':if(!q.confirm)throw Error('Confirmation required');return {message:child('tools/reference.cjs','update')};default:throw Error('Unknown manager action');}}
module.exports={run,adoptPreview,adopt,checked,create,generate,validateFormal,pending};
if(require.main===module)try{console.log(JSON.stringify(run(read(process.argv[2]))));}catch(e){console.error('MANAGER FAILED: '+e.message);process.exitCode=1;}
