'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),Ajv=require('ajv'),R=require('./release.cjs');
const ROOT=R.ROOT,DIR=path.join(ROOT,'config/profiles'),read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const canonical=x=>JSON.stringify(Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))));
const profileSchema={type:'object',additionalProperties:false,required:['id','name','mode','targetJlptLevel','vocabularyPerDay','grammarPerDay','readingQuestionsPerDay','listeningQuestionsPerDay','vocabularyWeight','grammarWeight','readingWeight','listeningWeight','readingStyle','listeningStyle','reviewPriority','createdAt','updatedAt','schemaVersion'],properties:{id:{type:'string',pattern:'^[a-z][a-z0-9-]{1,63}$'},name:{type:'string',minLength:1,maxLength:100},mode:{enum:['official','experiment']},targetJlptLevel:{enum:['N5','N4','N3','N2','N1']},schemaVersion:{const:1},createdAt:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}T'},updatedAt:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}T'},extensions:{type:'object',additionalProperties:false,properties:{kanjiEmphasis:{enum:['low','normal','high']},speakingEmphasis:{enum:['low','normal','high']},reviewRatio:{type:'number',minimum:0,maximum:1},mockFrequencyDays:{type:'integer',minimum:1,maximum:90},maxDailyMinutes:{type:'integer',minimum:10,maximum:480},reviewWeights:{type:'object',additionalProperties:false,properties:{d1:{type:'number',minimum:0},d3:{type:'number',minimum:0},d7:{type:'number',minimum:0}}}}}}};
for(const k of ['vocabularyPerDay','grammarPerDay','readingQuestionsPerDay','listeningQuestionsPerDay'])profileSchema.properties[k]={type:'integer',minimum:1,maximum:k==='vocabularyPerDay'?100:30};for(const k of ['vocabularyWeight','grammarWeight','readingWeight','listeningWeight','reviewPriority'])profileSchema.properties[k]={enum:['low','normal','high']};for(const k of ['readingStyle','listeningStyle'])profileSchema.properties[k]={enum:['jlpt-n5','jlpt-n4','jlpt-n3','jlpt-n2','jlpt-n1']};
const check=new Ajv({allErrors:true}).compile(profileSchema);
function validate(p){if(!check(p))throw Error('Invalid Profile: '+JSON.stringify(check.errors));if(p.id==='official-default'&&p.mode!=='official')throw Error('Official Default must remain official');return p;}
function file(id){if(!/^[a-z][a-z0-9-]{1,63}$/.test(id))throw Error('Invalid profile id');return path.join(DIR,id+'.json');}
function load(id){return validate(read(file(id)));}
function save(p,{create=false}={}){validate(p);fs.mkdirSync(DIR,{recursive:true});const dest=file(p.id),existing=fs.existsSync(dest)?load(p.id):null;if(create&&existing)throw Error('Profile already exists');if(existing&&existing.mode==='official'&&p.mode!=='official')throw Error('Cannot convert official profile; Save As experiment');const out={...p,createdAt:existing?.createdAt||p.createdAt,updatedAt:new Date().toISOString()};R.writeChanged(ROOT,{['config/profiles/'+out.id+'.json']:JSON.stringify(out,null,2)+'\n','config/active-profile.json':JSON.stringify({id:out.id},null,2)+'\n'});return out;}
function remove(id,confirmed){const p=load(id);if(p.mode==='official')throw Error('Official profiles cannot be deleted');if(!confirmed)throw Error('Delete requires confirmation');fs.unlinkSync(file(id));const active=read(path.join(ROOT,'config/active-profile.json'));if(active.id===id)select('official-default');return {deleted:id};}
function select(id){const p=load(id);R.writeChanged(ROOT,{'config/active-profile.json':JSON.stringify({id},null,2)+'\n'});return p;}
function binding(id){const p=load(id);return {profileId:p.id,profileName:p.name,profileMode:p.mode,profilePath:'config/profiles/'+p.id+'.json',profileSchemaVersion:p.schemaVersion,profileHash:hash(canonical(p)),parameters:structuredClone(p)};}
function validateBinding(b,mode){if(!b||b.profileMode!==mode||b.profileId!==b.parameters?.id||b.profileName!==b.parameters?.name||b.profileSchemaVersion!==1||b.profilePath!=='config/profiles/'+b.profileId+'.json'||b.profileHash!==hash(canonical(validate(b.parameters)))||b.parameters.mode!==mode)throw Error('Invalid immutable profile binding');return b;}
function coverage(){const W=require('./workflow.cjs'),refs=require('./reference.cjs').load(),files=R.capture(),weeks=R.validate(files).weeks,m=W.mapping(files,refs.rows),ids=new Set(m.entries.map(e=>e.referenceId).filter(Boolean));const asOf=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),days=Math.max(0,Math.ceil((Date.parse('2026-12-06')-Date.parse(asOf))/86400000));const types={};for(const type of ['vocab','grammar','kanji']){const all=refs.rows.filter(r=>r.type===type&&Object.values(r.jlpt.bySource).flat().includes('N2')),covered=type==='kanji'?null:all.filter(r=>ids.has(r.id)).length;types[type]={n2Candidates:all.length,resolvedN2:all.filter(r=>r.jlpt.resolved==='N2').length,coveredStableIds:covered,uncovered:covered===null?null:all.length-covered,levelConflicts:all.filter(r=>r.jlpt.resolved===null).length,unmappedCourseItems:m.entries.filter(e=>e.type===type&&!e.referenceId).length};}const result={schemaVersion:1,asOf,examDate:'2026-12-06',daysAvailable:days,formalWeeks:weeks.map(w=>w.week),latestFormalDay:weeks.at(-1).days.at(-1).day,referenceSnapshot:refs.index.version,courseSignature:R.signature(Object.fromEntries(Object.entries(files).filter(([p])=>!p.startsWith('data/experiments/')&&!['data/client-dictionary.json','data/publication.json'].includes(p)))),types,forecasts:[12,15,18,20].map(rate=>({newWordsPerDay:rate,capacity:rate*days,possibleAdditionalCoverage:Math.min(rate*days,types.vocab.uncovered),remainingGap:Math.max(0,types.vocab.uncovered-rate*days)})),assumptions:['N2 candidate means at least one source assigns N2; conflicts separately counted.','Coverage uses stable IDs and conservative unique historical mappings, not mastery; unresolved historical items may make the gap look larger.','Kanji formal instructional coverage is unknown, not zero.','Optimistic daily capacity includes today, excludes exam day, assumes no rest/review-only days and all new words are distinct N2 candidates. Experiments are excluded.']};R.writeChanged(ROOT,{'reports/n2-coverage.json':JSON.stringify(result,null,2)+'\n'});return result;}
function context(id,week){const b=binding(id),W=require('./workflow.cjs');W.context(week);const p=read(path.join(ROOT,'reports/work-context.json'));Object.assign(p,b,{profileBinding:structuredClone(b),n2Coverage:coverage(),generationMode:b.profileMode});if(b.profileMode==='experiment'){p.next={experiment:true,suggestedSessions:1,date:p.exam.asOf};p.rules.push('Create an experiment draft only; no official Week/Day numbers or official promotion.');}p.rules.push('Profile explicit quantities/weights override generic workload defaults, never truthful learner state, no duplicate-new rules, or provenance/validation.');if(Buffer.byteLength(JSON.stringify(p,null,2))>120000)throw Error('Profile context exceeds 120KB');R.writeChanged(ROOT,{'reports/work-context.json':JSON.stringify(p,null,2)+'\n'});return {file:'reports/work-context.json',...b};}
module.exports={profileSchema,validate,load,save,remove,select,binding,validateBinding,coverage,context,canonical,hash};
if(require.main===module)try{const [cmd]=process.argv.slice(2),opt=Object.fromEntries(process.argv.slice(3).filter(x=>x.startsWith('--')).map(x=>{const i=x.indexOf('=');return [x.slice(2,i),x.slice(i+1)];}));let out;if(cmd==='list')out={active:read(path.join(ROOT,'config/active-profile.json')).id,profiles:fs.readdirSync(DIR).filter(x=>x.endsWith('.json')).map(x=>load(x.slice(0,-5)))};else if(cmd==='load')out=select(opt.id);else if(cmd==='save')out=save(read(path.resolve(ROOT,opt.file)),{create:opt.create==='true'});else if(cmd==='delete')out=remove(opt.id,opt.confirm==='true');else if(cmd==='copy'){const p=load(opt.id);out=save({...p,id:opt.to,name:opt.name||p.name+' copy',mode:'experiment',createdAt:new Date().toISOString()},{create:true});}else if(cmd==='coverage')out=coverage();else if(cmd==='context')out=context(opt.id||read(path.join(ROOT,'config/active-profile.json')).id,Number(opt.week)||R.validate(R.capture()).weeks.at(-1).week+1);else throw Error('Use list/load/save/copy/delete/coverage/context');console.log(JSON.stringify(out,null,2));}catch(e){console.error('PLAN FAILED: '+e.message);process.exitCode=1;}
