# Plan Lab controls; files are persisted by the validated Node backend.
$script:planProfile=$null;$script:planNew=$false;$script:planFields=@{}
$profileList=New-Object System.Windows.Forms.ComboBox;$profileList.DropDownStyle='DropDownList';$profileList.SetBounds(20,15,360,30);$planTab.Controls.Add($profileList)
$profileModeLabel=New-Object System.Windows.Forms.Label;$profileModeLabel.SetBounds(400,18,420,26);$planTab.Controls.Add($profileModeLabel)
function Refresh-ProfileList {
 $profileList.Items.Clear();Get-ChildItem -LiteralPath (Join-Path $root 'config/profiles') -Filter '*.json' | ForEach-Object {[void]$profileList.Items.Add($_.BaseName)}
 if($script:planProfile){$profileList.SelectedItem=$script:planProfile.id}
}
function Fill-Profile($p){$script:planProfile=$p;$script:planNew=$false;foreach($name in $script:planFields.Keys){$c=$script:planFields[$name];if($c -is [System.Windows.Forms.NumericUpDown]){$c.Value=$p.$name}else{$c.Text=[string]$p.$name}};$profileModeLabel.Text=if($p.mode -eq 'official'){'【正式计划】 '+$p.name}else{'【实验计划】 '+$p.name};$script:planFields.id.ReadOnly=$true;Refresh-ProfileList}
function Start-PlanJob($file,$mode,$label){if($script:job){return};$script:afterJob={if($script:lastJobCode -eq 0){try{$result=$script:stdout.Result | ConvertFrom-Json;if($result.id -and $result.vocabularyPerDay){Fill-Profile $result};if($result.deleted){Fill-Profile (Get-Content -Raw -Encoding UTF8 (Join-Path $root 'config/profiles/official-default.json') | ConvertFrom-Json)}}catch{};Refresh-ProfileList};$planLog.Text=$script:output.Text;Show-Coverage};Start-JobUI $file $mode $label;$planLog.Text='运行中：'+$label}
function Test-PlanDirty {foreach($name in $script:planFields.Keys){if([string]$script:planFields[$name].Text -ne [string]$script:planProfile.$name){return $true}};return $false}
function Save-Plan($copy){if($script:job){return};$p=$script:planProfile | ConvertTo-Json -Depth 10 | ConvertFrom-Json;foreach($name in $script:planFields.Keys){$c=$script:planFields[$name];$p.$name=if($c -is [System.Windows.Forms.NumericUpDown]){[int]$c.Value}else{$c.Text}};$create=$script:planNew;if($copy){$id=[Microsoft.VisualBasic.Interaction]::InputBox('新 Profile ID（英文小写、数字、连字符）','另存为实验计划','experiment-copy');if(!$id){return};$p.id=$id;$p.name+='（副本）';$p.mode='experiment';$p.createdAt=(Get-Date).ToUniversalTime().ToString('o');$create=$true};$p | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath (Join-Path $root '.sync/profile-request.json') -Encoding UTF8;Start-PlanJob 'tools/plan.cjs' ('save --file=.sync/profile-request.json --create='+$create.ToString().ToLower()) '保存 Profile'}
function Plan-Button($label,$x,$y,$handler,$width=126){$b=New-Object System.Windows.Forms.Button;$b.Text=$label;$b.SetBounds($x,$y,$width,34);$b.Add_Click($handler);$planTab.Controls.Add($b);$script:buttons+=,$b}
Plan-Button '新建 Profile' 20 52 {$p=Get-Content -Raw -Encoding UTF8 (Join-Path $root 'config/profiles/official-default.json') | ConvertFrom-Json;$p.id='experiment-'+(Get-Date -Format yyyyMMddHHmmss);$p.name='新实验计划';$p.mode='experiment';$p.createdAt=(Get-Date).ToUniversalTime().ToString('o');Fill-Profile $p;$script:planNew=$true;$script:planFields.id.ReadOnly=$false}
Plan-Button '读取 Profile' 154 52 {if($profileList.SelectedItem){Start-PlanJob 'tools/plan.cjs' ('load --id='+$profileList.SelectedItem) '读取 Profile'}}
Plan-Button '保存' 288 52 {Save-Plan $false}
Plan-Button '另存为' 422 52 {Save-Plan $true}
Plan-Button '复制' 556 52 {Save-Plan $true}
Plan-Button '删除实验 Profile' 690 52 {if(!$script:planProfile){return};if($script:planProfile.mode -eq 'official'){[void][System.Windows.Forms.MessageBox]::Show('正式 Profile 禁止删除。');return};if([System.Windows.Forms.MessageBox]::Show('删除当前实验 Profile？已发布实验课程不受影响。','确认删除','YesNo') -eq 'Yes'){Start-PlanJob 'tools/plan.cjs' ('delete --id='+$script:planProfile.id+' --confirm=true') '删除 Profile'}} 155
$fields=@(@('id','Profile ID','text'),@('name','计划名称','text'),@('mode','计划模式','official,experiment'),@('targetJlptLevel','目标 JLPT','N5,N4,N3,N2,N1'),@('vocabularyPerDay','每日新词','number'),@('grammarPerDay','每日新语法','number'),@('readingQuestionsPerDay','每日阅读题','number'),@('listeningQuestionsPerDay','每日听力题','number'),@('vocabularyWeight','Vocabulary 权重','low,normal,high'),@('grammarWeight','Grammar 权重','low,normal,high'),@('readingWeight','Reading 权重','low,normal,high'),@('listeningWeight','Listening 权重','low,normal,high'),@('readingStyle','阅读目标难度','jlpt-n5,jlpt-n4,jlpt-n3,jlpt-n2,jlpt-n1'),@('listeningStyle','听力目标难度','jlpt-n5,jlpt-n4,jlpt-n3,jlpt-n2,jlpt-n1'),@('reviewPriority','复习优先级','low,normal,high'))
for($i=0;$i -lt $fields.Count;$i++){$f=$fields[$i];$x=20+420*($i%2);$y=100+38*[math]::Floor($i/2);$l=New-Object System.Windows.Forms.Label;$l.Text=$f[1];$l.SetBounds($x,$y+5,145,28);$planTab.Controls.Add($l);if($f[2] -eq 'number'){$c=New-Object System.Windows.Forms.NumericUpDown;$c.Minimum=1;$c.Maximum=if($f[0] -eq 'vocabularyPerDay'){100}else{30}}elseif($f[2] -eq 'text'){$c=New-Object System.Windows.Forms.TextBox}else{$c=New-Object System.Windows.Forms.ComboBox;$c.DropDownStyle='DropDownList';foreach($o in $f[2].Split(',')){[void]$c.Items.Add($o)}};$c.SetBounds($x+150,$y,235,30);$planTab.Controls.Add($c);$script:planFields[$f[0]]=$c}
Plan-Button 'N2 覆盖与预测' 20 418 {Start-PlanJob 'tools/plan.cjs' 'coverage' 'N2 覆盖分析'} 185
Plan-Button '生成 Work Context' 220 418 {if($script:planNew -or (Test-PlanDirty)){[void][System.Windows.Forms.MessageBox]::Show('请先保存 Profile。');return};Start-PlanJob 'tools/plan.cjs' ('context --id='+$script:planProfile.id) '生成绑定 Profile 的 Context'} 185
Plan-Button '新建实验草稿' 420 418 {if($script:planNew -or (Test-PlanDirty)){[void][System.Windows.Forms.MessageBox]::Show('请先保存 Profile 修改。');return};if($script:planProfile.mode -ne 'experiment'){[void][System.Windows.Forms.MessageBox]::Show('请先选择并保存实验 Profile。');return};$id=[Microsoft.VisualBasic.Interaction]::InputBox('实验 ID，以 experiment- 开头','新建空白实验草稿','experiment-first');if($id){Start-PlanJob 'tools/experiments.cjs' ('new --profile='+$script:planProfile.id+' --id='+$id) '创建空白草稿（由 Work 填写）'}} 185
Plan-Button '校验/更新实验课程' 620 418 {$dialog=New-Object System.Windows.Forms.OpenFileDialog;$dialog.InitialDirectory=Join-Path $root 'data/drafts/experiments';$dialog.Filter='JSON (*.json)|*.json';if($dialog.ShowDialog() -eq 'OK'){if([System.Windows.Forms.MessageBox]::Show('校验通过后晋升为实验课程？不会生成或修改正式 Week。','确认实验晋升','YesNo') -eq 'Yes'){Start-PlanJob 'tools/experiments.cjs' ('promote --file="'+$dialog.FileName+'"') '校验并晋升实验课程'}};$dialog.Dispose()} 225
$coverageText=New-Object System.Windows.Forms.Label;$coverageText.SetBounds(20,465,830,115);$planTab.Controls.Add($coverageText)
function Show-Coverage {try{$r=Get-Content -Raw -Encoding UTF8 -LiteralPath (Join-Path $root 'reports/n2-coverage.json') | ConvertFrom-Json;$coverageText.Text='N2 词汇：'+$r.types.vocab.coveredStableIds+' / '+$r.types.vocab.n2Candidates+'；未确认覆盖 '+$r.types.vocab.uncovered+'。语法：'+$r.types.grammar.coveredStableIds+' / '+$r.types.grammar.n2Candidates+[Environment]::NewLine+'汉字候选 '+$r.types.kanji.n2Candidates+'；独立教学覆盖 unknown。距离考试 '+$r.daysAvailable+' 天。'+[Environment]::NewLine+(($r.forecasts | ForEach-Object {$_.newWordsPerDay.ToString()+'词/天 → '+$_.possibleAdditionalCoverage+' 候选'}) -join '；')+[Environment]::NewLine+'理论上限，未扣复习/休息日；历史未匹配项不视为掌握。'}catch{$coverageText.Text='点击 N2 覆盖与预测，读取本地数据计算。'}}
$planLog=New-Object System.Windows.Forms.TextBox;$planLog.Multiline=$true;$planLog.ReadOnly=$true;$planLog.ScrollBars='Vertical';$planLog.SetBounds(20,580,825,100);$planLog.Anchor='Top,Bottom,Left,Right';$planTab.Controls.Add($planLog)
Add-Type -AssemblyName Microsoft.VisualBasic
Refresh-ProfileList
$active=Get-Content -Raw -Encoding UTF8 -LiteralPath (Join-Path $root 'config/active-profile.json') | ConvertFrom-Json
Fill-Profile (Get-Content -Raw -Encoding UTF8 -LiteralPath (Join-Path $root ('config/profiles/'+$active.id+'.json')) | ConvertFrom-Json)
Show-Coverage
